driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.8.1
  attributes:
    firewall:
      allow_ssh: true
      allow_winrm: true
      firewalld:
        permanent: true

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.10
    run_list:
      - recipe[apt]
  - name: debian-8.4
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: windows-2012r2
    driver_config:
      box: windows2012r2

suites:
  - name: default
    run_list:
      - recipe[firewall::default]
      - recipe[firewall-test::default]

  - name: iptables
    excludes:
      - centos-5.11
      - centos-6.7
      - debian-7.10
      - debian-8.4
      - windows-2012r2
    run_list:
      - recipe[firewall-test::default]
    attributes:
      firewall:
        ubuntu_iptables: true
        redhat7_iptables: true
